# -*- coding: utf-8 -*-
"""hw_010_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y55RQJ2HittNJm_jQaq8yghKTZx-mrGd
"""

import pandas as pd

import random

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst) # возвращает перемешанный список
data = pd.DataFrame({'whoAmI':lst})
data.head(20)

# pd.get_dummies(data, columns=['whoAmI'], drop_first=False)

import numpy as np

data['robot'] = np.where(data['whoAmI'] == 'robot', 1, 0)
data['human'] = np.where(data['whoAmI'] == 'human', 1, 0)
data = data.drop(columns='whoAmI')

data

